import time
import subprocess
import os

subprocess.Popen(["firefox", "https://youtu.be/sQSbsBu2gCU"])
time.sleep(150)
os.system('pkill firefox')
subprocess.Popen(["firefox", "https://youtu.be/Q_ICerggIpI"])
time.sleep(250)
os.system('pkill firefox')
subprocess.Popen(["firefox", "https://youtu.be/fLoSpepEIqw"])
time.sleep(190)
os.system('pkill firefox')
subprocess.Popen(["firefox", "https://youtu.be/KcjSLzi3Yvc"])
time.sleep(140)
os.system('pkill firefox')
subprocess.Popen(["firefox", "https://youtu.be/F6m8PbPvCzE"])
time.sleep(280)
os.system('pkill firefox')
subprocess.Popen(["firefox", "https://youtu.be/B4aT4k_RHw0"])
time.sleep(230)
os.system('pkill firefox')
subprocess.Popen(["firefox", "https://youtu.be/SZOYTpfQ1ik"])
time.sleep(190)
os.system('pkill firefox')
subprocess.Popen(["firefox", "https://youtu.be/do2I88UCreQ"])
time.sleep(290)
os.system('pkill firefox')
subprocess.Popen(["firefox", "https://youtu.be/eyVLCNtWFXk"])
time.sleep(250)
os.system('pkill firefox')
subprocess.Popen(["firefox", "https://youtu.be/CLRXW3chq2c"])
time.sleep(200)
os.system('pkill firefox')
subprocess.Popen(["firefox", "https://youtu.be/28B_5D94l58"])
time.sleep(200)
os.system('pkill firefox')
subprocess.Popen(["firefox", "https://youtu.be/E9Fxg8f3rJM"])
time.sleep(200)
os.system('pkill firefox')
subprocess.Popen(["firefox", "https://youtu.be/eLz0tFnEQtg"])
time.sleep(200)
os.system('pkill firefox')
